name: Discord Webhook Submission
description: Submit a request using Discord Webhook and Content IDs
title: "[Webhook Request]: "
body:
  - type: input
    id: discord_webhook
    attributes:
      label: Discord Webhook URL
      description: Please enter the Discord webhook URL.
      placeholder: "https://discord.com/api/webhooks/..."
    validations:
      required: true
  - type: input
    id: content_id_1
    attributes:
      label: Content ID 1
      description: Enter the first content ID.
      placeholder: "12345"
    validations:
      required: true
  - type: input
    id: content_id_2
    attributes:
      label: Content ID 2
      description: Enter the second content ID.
      placeholder: "12345"
    validations:
      required: true
  - type: input
    id: content_id_3
    attributes:
      label: Content ID 3
      description: Enter the third content ID.
      placeholder: "12345"
    validations:
      required: true
  - type: input
    id: content_id_4
    attributes:
      label: Content ID 4
      description: Enter the fourth content ID.
      placeholder: "12345"
    validations:
      required: true
  - type: input
    id: content_id_5
    attributes:
      label: Content ID 5
      description: Enter the fifth content ID.
      placeholder: "12345"
    validations:
      required: true
